# Generated by Django 2.1.5 on 2019-02-04 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190204_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 12, 15, 39, 557928), verbose_name='date published'),
        ),
    ]
